### ISSUE TITLE
All tag was O for the given data

### ISSUE THREAD

**Issue by eclipse-du** [glample/tagger#49] opened 2017-05-03 07:56 UTC
Dear Glample,

When i have tried to train the model using the data you provided, i got the error infomation like this:
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1851915.scores'

By the way, i've checked the output. All the result was O tag, which makes me confuse.
Here is my command line:
./train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb

With Regards,
A du.

**Comment by glample** [comment] 2017-05-05 10:07
Hi,

I'm not sure I understand. How was the 'eval.1851915.scores' file created? Was is using train.py or tagger.py? If you used tagger.py, did you tokenize the file properly? Also note that the input file formats are different for train.py (one word by line) and tagger.py (one sentence by line).

**Comment by rikuge** [comment] 2017-05-06 21:34
When running python train.py --train dataset/eng.train --dev dataset/eng.testa --test dataset/eng.testb, after a few epochs i receive the same error: 

  File "train.py", line 220, in <module>
    dev_data, id_to_tag, dico_tags)
  File "./tagger-master/utils.py", line 256, in evaluate
    eval_lines = [l.rstrip() for l in codecs.open(scores_path, 'r', 'utf8')]
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1740643.scores'

For the previous epochs there are .scores and .output files in temp, but i can't trace back the error. I'm using the provided training and test sets.

Regards,
rikuge

**Comment by onurgu** [comment] 2017-05-07 09:24
Maybe you have ran out of disk space?

Did you move the `utils.py` to a subdirectory? This might be the case.

**Comment by rikuge** [comment] 2017-05-07 16:51
Neither..  i just downloaded the code and ran the it, changed nothing. After train.py creates a few .output and .scores files it is no longer able to create the .scores file (the .output file is present).

**Comment by marcevrard** [comment] 2017-05-09 10:24
I've experienced the same issue during training, the recurrent evaluation failed also at some point with a: "No such file or directory: './evaluation/temp/eval.***.scores". 
It happens on the vanilla version of the code after some iterations (at iteration 7000 during epoch 2 on my side). There is still a lot of space left on my drive.

It happens with the Theano-0.9.0 version and seems correlated to the RAM memory steady increase during training. It seems to work fine with Theano-0.7.0.

@glample, could you tell us which version of Theano you were using? I guess it wasn't the 0.9.0 since the code was committed last year.

**Comment by glample** [comment] 2017-05-09 12:47
Hi,

Yes, I was using theano 0.7 at the time. I think 0.8 came out at about the same time I released the code, and there was no issue back then. I'm surprised you observe a RAM memory increase with theano 0.9, if this happens I would imagine the problem is coming from this version of theano, maybe a temporary bug. If this is not a problem of theano I will need to fix the tagger code, but I'm really sorry I don't have time to investigate on this currently :(

**Comment by marcevrard** [comment] 2017-05-10 07:58
Hi @glample 
Indeed, I tested with `theano-0.8.2` and it works as well.
It's most likely related to the issue identified and fixed here:
http://stackoverflow.com/q/43234170/4218883
https://github.com/Theano/Theano/issues/5810
https://github.com/Theano/Theano/pull/5832
So no problem in the code, it's in `theano-0.9.0` apparently.
Cheers

**Comment by Woooooody** [comment] 2017-05-18 08:38
Hi @glample
     when I have trained model use Chinese data, I got the error information in epoch 15 :IOError: [Errno 2] No such file or directory: './evaluation/temp/eval.1742145.scores'.I'm sure my data formats are same as you require,but I can't track back the error.
   Regards,
   Woody
---------------------------------------------------------------------------------------
I find it in theano-0.8.* it is works as well too,thanks for share:) @marcevrard

**Comment by ghost** [comment] 2017-06-29 19:08
Dear Glample,

I am trying to train my own model and I am not able to go through this error which is being generated ,
![capture](https://user-images.githubusercontent.com/6318396/27705776-f346a95e-5cdc-11e7-9b87-be8cb9c6b355.PNG)


I am not able to figure it out why i am getting that error.
it seems like the below shell command we are trying to run utils.py has some issue
os.system("%s < %s > %s" % (eval_script, output_path, scores_path)).

But i am not sure what exactly we are trying to achieve here with this command

**Comment by ghost** [comment] 2017-07-12 13:12
I am also facing the same issue. All my predictions are O, eventhough i am using theano-0.8*. Can anyone help me on whats wrong i might be doing.

**Closed as completed** 2018-01-01 13:49 UTC
